security:
    # Configuration des hashers de mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Configuration des fournisseurs d'utilisateurs
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_parameter: _csrf_token
                username_parameter: login_form[_username]
                password_parameter: login_form[_password]


            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/figure/.*/edit, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/figure/new, roles: IS_AUTHENTICATED_FULLY }
