parameters:
    media_directory: '%kernel.project_dir%/public/uploads/media'

services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés, etc.
        public: false       # Les services ne sont pas publics par défaut

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
